<?php

function saveSanPham($node){
  if($node->type == 'san_pham'){
    global $user;
    $curl = curl_init();
    curl_setopt_array($curl, array(
      CURLOPT_URL => 'https://app.hpmap.vn/service/save-san-pham',
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_ENCODING => '',
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 0,
      CURLOPT_FOLLOWLOCATION => true,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => 'POST',
      CURLOPT_POSTFIELDS => json_encode([
        'uid' => $user->uid,
        'title' => $node->title,
        'form_token' => $node->form_token,
        'nid' => $node->nid,
        'token' => md5(md5(date('YmdHi').$user->uid.$node->title.$node->nid.$node->form_token.'MHS')),
        'node' => $node
      ]),
      // md5(md5($dateTime.$obj['ui'].$obj['title'].$obj['nid'].$obj['form_token'].'MHS'));
      CURLOPT_HTTPHEADER => array(
        'Content-Type: application/json'
      ),
    ));

    $response = curl_exec($curl);
    curl_close($curl);
  }
}
/**
 * Implements hook_node_insert().
 */
function hpmap_node_insert($node)
{
    saveSanPham($node);
}
function unpublished_node($nid){
    $node = node_load($nid);
    $node->status = 0;
    node_save($node);
}

/**
 * Implements hook_node_update().
 */
function hpmap_node_update($node)
{
    $node->status= 0;
    field_attach_update('node', $node);
    saveSanPham($node);
}

function getKhuVuc($type){
  $curl = curl_init();
  global $user;
//"{\n\t\"uid\": 170,\n\t\"type\": \"Thành phố\",\n\t\"token\": \"02934029432409240zvzxcv\"\n}"
  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://app.hpmap.vn/service/get-khu-vuc",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS => json_encode([
      'uid' => $user->uid,
      'type' => $type,
      'token' => md5(md5(date('YmdHi').$user->uid.'MHS'))
    ]),
    CURLOPT_HTTPHEADER => array(
      "cache-control: no-cache",
      "content-type: application/json",
      "postman-token: 6069a2d7-1994-fa28-aa79-d44b6da55adf"
    ),
  ));

  $response = curl_exec($curl);
  $err = curl_error($curl);

  curl_close($curl);

  if ($err) {
    return $err;
  } else {
    return $response;
  }
}

function getThanhVien($nid){
  $curl = curl_init();
  global $user;
//"{\n\t\"uid\": 170,\n\t\"type\": \"Thành phố\",\n\t\"token\": \"02934029432409240zvzxcv\"\n}"
  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://app.hpmap.vn/service/get-info-relation",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS => json_encode([
        'nid' => $nid,
    ]),
    CURLOPT_HTTPHEADER => array(
      "cache-control: no-cache",
      "content-type: application/json",
      "postman-token: 6069a2d7-1994-fa28-aa79-d44b6da55adf"
    ),
  ));

  $response = curl_exec($curl);
  $err = curl_error($curl);

  curl_close($curl);

  if ($err) {
    return $err;
  } else {
    return json_decode($response, true);
  }
}

function getThongTinSanPham($idSanPham){
  $curl = curl_init();
  global $user;
    $token = md5(md5(date('YmdH').$user->uid.'MHS'));
//"{\n\t\"uid\": 170,\n\t\"type\": \"Thành phố\",\n\t\"token\": \"02934029432409240zvzxcv\"\n}"
  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://app.hpmap.vn/service/get-thong-tin-san-pham",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS => json_encode([
        'uid' => $user->uid,
        'token' => $token,
        'san_pham' => $idSanPham,
    ]),
    CURLOPT_HTTPHEADER => array(
      "cache-control: no-cache",
      "content-type: application/json",
      "postman-token: 6069a2d7-1994-fa28-aa79-d44b6da55adf"
    ),
  ));

  $response = curl_exec($curl);
  $err = curl_error($curl);

  curl_close($curl);

  if ($err) {
    return $err;
  } else {
    return json_decode($response, true);
  }
}

/**
 * Implements hook_form_alter().
 */
function hpmap_form_alter(&$form, &$form_state, $form_id)
{
  global $user;
  $token = md5(md5(date('YmdH').$user->uid.'MHS'));
  if($form_id =='san_pham_node_form'){
    //    $form['#prefix'] = '<input type="hidden" id="input-uid" value="'.$user->uid.'">'.(date('YmdH').$user->uid.'MHS').'<input type="hidden" id="input-token" value="'.$token.'">';
    //    $data = json_decode(getKhuVuc('Thành phố'));
    //    $options = [
    //      '' => '-- Chọn Tỉnh / TP --'
    //    ];
    //    foreach ($data as $item){
    //      $options[$item->id] = $item->name;
    //    }
    //    $form['field_thanh_pho']['und']['#options'] = $options;
    $form['#prefix']='<div class="row"><div class="col-md-2"></div><div class="col-md-8">';
    $form['#suffix']='</div><div class="col-md-2"></div></div>';
    $form['title']['#prefix']='<h3 class="title-dien-thong-tin text-center mt-20">Điền thông tin</h3><div class="title_thong_tin"><h4>Thông tin liên hệ</h4> <hr> </div><div class="row"><div class="col-md-12">';
    $form['title']['#suffix']='</div></div>';
    $form['title']['#attributes']['class'] = array('form-control');
    $form['title']['#title'] = t('Tiêu đề');

    $form['field_ho_ten_chu_nha']['#prefix']  = t('<div class="row"><div class="col-md-6 col-6">');
    $form['field_ho_ten_chu_nha']['#suffix'] = t('</div>');

    $form['field_dien_thoai_chu_nha']['#prefix'] = t('<div class="col-md-6 col-6">');
    $form['field_dien_thoai_chu_nha']['#suffix'] = t('</div></div>');

    $form['field_dien_thoai_chu_nha']['und'][0]['value']['#attributes']['class'] = array('form-control ');
    $form['field_ho_ten_chu_nha']['und'][0]['value']['#attributes']['class'] = array('form-control ');

    $form['field_thanh_pho']['#attributes']['class'] = array('d-none');

    $form['field_quan_huyen']['#prefix'] = t('<div class="row"><div class="col-md-6 col-6">');
    $form['field_quan_huyen']['#suffix'] = t('</div>');

    $form['field_duong_pho']['#prefix'] = t('<div class="col-md-6 col-6">');
    $form['field_duong_pho']['#suffix'] = t('</div></div>');

    $form['field_chieu_dai_mb']['#prefix'] = t('<div class="title_thong_tin mt-20"><h4>Thông số</h4> <hr> </div><div class="row"><div class="col-md-6 col-6">');
    $form['field_chieu_dai_mb']['#suffix'] = t('</div>');
    $form['field_chieu_rong']['#prefix'] = t('<div class="col-md-6 col-6">');
    $form['field_chieu_rong']['#suffix'] = t('</div></div>');
    $form['field_dien_tich_su_dung']['#prefix'] = t('<div class="row"><div class="col-md-6 col-6">');
    $form['field_dien_tich_su_dung']['#suffix'] = t('</div>');
    $form['field_dien_tich_mat_bang']['#prefix'] = t('<div class="col-md-6 col-6">');
    $form['field_dien_tich_mat_bang']['#suffix'] = t('</div></div>');

    $form['field_lien_he']['#prefix'] = t('<div class="row mt-30"><div class="d-none">');
    $form['field_lien_he']['#suffix'] = t('</div>');
    $form['field_phap_ly']['#prefix'] = t('<div class="col-md-6 col-6">');
    $form['field_phap_ly']['#suffix'] = t('</div></div>');
    $form['field_ngay_dang']['#prefix'] = t('<div class="col-md-6">');
    $form['field_ngay_dang']['#suffix'] = t('</div></div>');
    $form['field_banner']['#attributes']['class']= array('mt-30');
    $form['field_tien_nghi_khac']['#prefix']='<div class="d-none">';
    $form['field_tien_nghi_khac']['#suffix']='</div>';
    $form['field_dien_tich_mat_bang']['und'][0]['value']['#attributes']['class'] = array('form-control');
    $form['field_dien_tich_su_dung']['und'][0]['value']['#attributes']['class'] = array('form-control');
    $form['field_chieu_dai_mb']['und'][0]['value']['#attributes']['class'] = array('form-control');
    $form['field_chieu_rong']['und'][0]['value']['#attributes']['class'] = array('form-control ');
    $form['field_lien_he']['und'][0]['value']['#attributes']['class'] = array('form-control ');
    $form['field_phap_ly']['und'][0]['value']['#attributes']['class'] = array('form-control ');
    $form['field_toa_do_vi_tri']['und'][0]['value']['#attributes']['class'] = array('form-control col-md-6');
    $form['field_danh_sach_cac_dinh']['und'][0]['value']['#attributes']['class'] = array('form-control');
    $form['actions']['submit']['#attributes']['class'] = array('btn btn-primary');
    $form['actions']['preview']['#attributes']['class'] = array('d-none');


    $form['field_gia']['#prefix'] = t('<div class="title_thong_tin mt-20"><h4>Giá</h4> <hr> </div><div class="row"><div class="col-md-6 col-6">');
    $form['field_gia']['#suffix'] = t('</div>');
    $form['field_khoang_gia_den']['#prefix'] = t('<div class="col-md-6 col-6">');
    $form['field_khoang_gia_den']['#suffix'] = t('</div>');
    $form['field_gia_bang_chu']['#prefix'] = t('<div class="col-md-12 col-12">');
    $form['field_gia_bang_chu']['#suffix'] = t('</div></div>');


    $form['field_so_giuong']['#prefix'] = t('<div class="title_thong_tin mt-20"><h4>Thông tin khác</h4> <hr> </div><div class="row"><div class="col-md-6 col-6">');
    $form['field_so_giuong']['#suffix'] = t('</div>');
    $form['field_so_phong_tam']['#prefix'] = t('<div class="col-md-6 col-6">');
    $form['field_so_phong_tam']['#suffix'] = t('</div></div>');

    $form['field_phan_loai']['#prefix'] = t('<div class="title_thong_tin mt-20"><h4>Phân loại và địa chỉ</h4> <hr> </div><div class="row"><div class="col-md-6 col-6">');
    $form['field_phan_loai']['#suffix'] = t('</div>');


    $form['field_gia']['und'][0]['value']['#attributes']['class'] = array('form-control ');
    $form['field_dia_chi_du_an']['#prefix'] = '<div class="row"><div class="col-md-6 col-6">';
    $form['field_dia_chi_du_an']['#suffix'] = '</div></div>';
    $form['field_dia_chi_du_an']['und'][0]['value']['#attributes']['class'] = array('form-control');
    $form['field_khoang_gia_den']['und'][0]['value']['#attributes']['class'] = array('form-control');
    $form['field_gia_bang_chu']['und'][0]['value']['#attributes']['class'] = array('form-control ');

    $form['field_so_giuong']['und'][0]['value']['#attributes']['class'] = array('form-control ');
    $form['field_so_phong_tam']['und'][0]['value']['#attributes']['class'] = array('form-control ');


    $form['field_tags']['#prefix'] = t('<div class="row"><div class="col-md-4">');
    $form['field_tags']['#suffix'] = t('</div></div>');
    $form['field_tags']['und']['#attributes']['class'] = array('form-control');

  }
  else if($form_id == 'user_register_form'){

  }else if ($form_id == 'user_profile_form'){
    $form['#submit'][] = 'hpmap_user_update_submit';
  }else if ($form_id == 'user-login'){
//    $form['#submit'][] = 'hpmap_user_presave';
  }
}

/**
 * Implements hook_user_login().
 */
function hpmap_user_login(&$edit, $account)
{
  global $user;
  $curl = curl_init();
  curl_setopt_array($curl, [
    CURLOPT_URL => 'https://app.hpmap.vn/service/generation-auth',
    CURLOPT_RETURNTRANSFER => TRUE,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => TRUE,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS => json_encode([
      "username" => $user->name,
    ]),
    CURLOPT_HTTPHEADER => [
      'Content-Type: application/json',
//      'Cookie: _csrf-backend=1d1f189315c04255c97019c8d04a18e4815e9ebf7d68c24e3bf690d637ab0396a%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_csrf-backend%22%3Bi%3A1%3Bs%3A32%3A%22z6qHzQbiby8jcKCzN5VICKAsiwfySN4u%22%3B%7D',
    ],
  ]);
  $response = curl_exec($curl);
  $err = curl_error($curl);
  curl_close($curl);
    if ($err) {
        return $err;
    }
    else {
        $data = json_decode($response, true);
        $edit['redirect'] = 'https://app.hpmap.vn/site/login?auth_key='.$data['auth_key'].'&user_name='.$user->name;
    return $response;
  }
}

function hpmap_login_soft(&$form, &$form_state){
    global $user;
    $curl = curl_init();
    curl_setopt_array($curl, [
        CURLOPT_URL => 'https://app.hpmap.vn/service/generation-auth',
        CURLOPT_RETURNTRANSFER => TRUE,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => TRUE,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'POST',
        CURLOPT_POSTFIELDS => json_encode([
            "username" => $user->name,
        ]),
        CURLOPT_HTTPHEADER => [
            'Content-Type: application/json',
            'Cookie: _csrf-backend=1d1f189315c04255c97019c8d04a18e4815e9ebf7d68c24e3bf690d637ab0396a%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_csrf-backend%22%3Bi%3A1%3Bs%3A32%3A%22z6qHzQbiby8jcKCzN5VICKAsiwfySN4u%22%3B%7D',
        ],
    ]);
    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    if ($err) {
        return $err;
    }
    else {
        $data = json_decode($response, true);
        drupal_goto('http://app.hpmap.vn/site/login?auth_key='.$data['auth_key'].'&user_name='.$user->name);
        return $response;
    }
}
/**
 * Implements hook_user_logout().
 */
function hpmap_user_logout($account)
{
    session_destroy();
    drupal_goto('http://app.hpmap.vn/site/logout');
}

function hpmap_user_register_submit(&$form, &$form_state){
//  global $user;
//  $token = md5(md5(date('YmdH').$user->uid.'MHS'));
//  $value = $form_state['values'];
//  $curl = curl_init();
//  curl_setopt_array($curl, [
//    CURLOPT_URL => 'https://app.hpmap.vn/service/save-user',
//    CURLOPT_RETURNTRANSFER => TRUE,
//    CURLOPT_ENCODING => '',
//    CURLOPT_MAXREDIRS => 10,
//    CURLOPT_TIMEOUT => 0,
//    CURLOPT_FOLLOWLOCATION => TRUE,
//    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
//    CURLOPT_CUSTOMREQUEST => 'POST',
//    CURLOPT_POSTFIELDS => json_encode([
//      "name" => $value['name'],
//      "field_ho_ten" => $value['field_ho_ten']['und'][0]['value'],
//      "field_so_dien_thoai_vn" => $value['field_so_dien_thoai_vn']['und'][0]['value'],
//      "field_dia_chi_du_an" => $value['field_dia_chi_du_an']['und'][0]['value'],
//      "pass" => $value['pass'],
//      "uid" => $value['uid'],
//      "uid_nguoi_tao" => $user->uid,
//      "token" => $token
//    ]),
//    CURLOPT_HTTPHEADER => [
//      'Content-Type: application/json',
//      'Cookie: _csrf-backend=1d1f189315c04255c97019c8d04a18e4815e9ebf7d68c24e3bf690d637ab0396a%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_csrf-backend%22%3Bi%3A1%3Bs%3A32%3A%22z6qHzQbiby8jcKCzN5VICKAsiwfySN4u%22%3B%7D'
//    ],
//  ]);
//  $response = curl_exec($curl);
//  $err = curl_error($curl);
//  curl_close($curl);
//    if ($err) {
//        return $err;
//    } else {
//
//        return json_decode($response, true);
//    }
}
function hpmap_user_update_submit(&$form, &$form_state){
  global $user;
  $token = md5(md5(date('YmdH').$user->uid.'MHS'));
  $value = $form_state['values'];
  $curl = curl_init();
  curl_setopt_array($curl, [
    CURLOPT_URL => 'https://app.hpmap.vn/service/update-user',
    CURLOPT_RETURNTRANSFER => TRUE,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => TRUE,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS => json_encode([
      "name" => $value['name'],
      "field_ho_ten" => $value['field_ho_ten']['und'][0]['value'],
      "field_so_dien_thoai_vn" => $value['field_so_dien_thoai_vn']['und'][0]['value'],
      "field_dia_chi_du_an" => $value['field_dia_chi_du_an']['und'][0]['value'],
      "pass" => $value['pass'],
      "uid" => $user->uid,
      "id" => $value['uid'],
      "token" => $token
    ]),
    CURLOPT_HTTPHEADER => [
      'Content-Type: application/json',
      'Cookie: _csrf-backend=1d1f189315c04255c97019c8d04a18e4815e9ebf7d68c24e3bf690d637ab0396a%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_csrf-backend%22%3Bi%3A1%3Bs%3A32%3A%22z6qHzQbiby8jcKCzN5VICKAsiwfySN4u%22%3B%7D'
    ],
  ]);
  $response = curl_exec($curl);
  curl_close($curl);
}

/**
 * Implements hook_user_presave().
 */
function hpmap_user_presave(&$edit, $account, $category)
{
    global $user;
    $users = entity_load('user');
    $myLastElement = end($users);
    $uid = $myLastElement->uid+1;
    if ($account->uid == 0){
        $uid_1 = $uid;
        $filename = '';
    }else
    {
        $uid_1 = $user->uid;
        $filename = 'https://hpmap.vn/sites/default/files/styles/large/public/pictures/'.$account->picture->filename;
    }
    $token = md5(md5(date('YmdH').$user->uid.'MHS'));
    $curl = curl_init();
    curl_setopt_array($curl, [
        CURLOPT_URL => 'https://app.hpmap.vn/service/save-user',
        CURLOPT_RETURNTRANSFER => TRUE,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => TRUE,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'POST',
        CURLOPT_POSTFIELDS => json_encode([
            "name" => $account->name,
            "field_ho_ten" => $account->field_ho_ten['und'][0]['value'],
            "field_so_dien_thoai_vn" => $account->field_so_dien_thoai_vn['und'][0]['value'],
            "field_dia_chi_du_an" => isset($account->field_dia_chi_du_an['und'][0]['value']) ? $account->field_dia_chi_du_an['und'][0]['value']: '',
            "pass" => $account->pass,
            "uid" => $uid_1,
            "uid_nguoi_tao" => $account->uid,
            "avatar" => $filename,
            "token" => $token
        ]),
        CURLOPT_HTTPHEADER => [
            'Content-Type: application/json',
            'Cookie: _csrf-backend=1d1f189315c04255c97019c8d04a18e4815e9ebf7d68c24e3bf690d637ab0396a%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_csrf-backend%22%3Bi%3A1%3Bs%3A32%3A%22z6qHzQbiby8jcKCzN5VICKAsiwfySN4u%22%3B%7D'
        ],
    ]);
    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    if ($err) {
        return $err;
    } else {
        return json_decode($response, true);

    }

}
/**
 * Implements hook_menu().
 */
function hpmap_menu()
{
  $items['tim-san-pham'] = array(
    'title' => 'Tìm kiếm sản phẩm',
    'delivery callback' => 'tim_kiem_san_pham',
    'access callback' => 'TRUE',
//        'access arguments' => array('get order'),
    'type' => MENU_CALLBACK
  );
  $items['get-thong-tin-chi-tiet-san-pham'] = array(
    'title' => 'Lấy thông tin chi tiết sản phẩm',
    'delivery callback' => 'get_thong_tin_chi_tiet_san_pham',
    'access callback' => 'TRUE',
    'access arguments' => array('get_thong_tin_chi_tiet_san_pham'),
    'type' => MENU_CALLBACK
  );
  $items['update-status-user'] = array(
    'title' => 'Set status user 0',
    'delivery callback' => 'update_status_user',
    'access callback' => 'TRUE',
    'access arguments' => array('update_status_user'),
    'type' => MENU_CALLBACK
  );
  $items['update-status-product'] = array(
    'title' => 'Set status user 0',
    'delivery callback' => 'update_status_product',
    'access callback' => 'TRUE',
    'access arguments' => array('update_status_product'),
    'type' => MENU_CALLBACK
  );
  $items['delete-product'] = array(
    'title' => 'delete product',
    'delivery callback' => 'delete_product',
    'access callback' => 'TRUE',
    'access arguments' => array('delete_product'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

function tim_kiem_san_pham(){
    global $user;
    $token = md5(md5(date('YmdH').$user->uid.'MHS'));
  header('Access-Control-Allow-Origin: *');
  header('Content-type: application/json');
  $obj = $_POST;
  if(count($obj) == 0){
    $dataPost = file_get_contents('php://input');
    $obj =json_decode($dataPost); // json::decode($dataPost);
  }
  $curl = curl_init();
  curl_setopt_array($curl, [
    CURLOPT_URL => 'https://app.hpmap.vn/service/tim-kiem-san-pham',
    CURLOPT_RETURNTRANSFER => TRUE,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => TRUE,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS => json_encode([
        "quan_huyen" => $obj['quan_huyen'],
        "duong_pho" => $obj['duong_pho'],
        "khoang_gia" => [$obj['khoang_gia']],
        "huong" => $obj['huong'],
        "khoang_dien_tich"=> [$obj['khoang_dien_tich']],
        "phan_loai" => [$obj['phan_loai']],
        "name" => $obj['name'],
    ]),
    CURLOPT_HTTPHEADER => [
      'Content-Type: application/json'
    ],
  ]);
  $response = curl_exec($curl);
  curl_close($curl);
  drupal_save_session(TRUE);
  $_SESSION['san_pham'] = $response;
  echo $response;
}

/**
 * Implements hook_user_presave().
 */
function hpmap_node_presave($node) {
//  global $user;
//  $token = md5(md5(date('YmdH').$user->uid.'MHS'));
//
//  $curl = curl_init();
//
//  curl_setopt_array($curl, array(
//    CURLOPT_URL => 'https://app.hpmap.vn/service/update-uid-user',
//    CURLOPT_RETURNTRANSFER => true,
//    CURLOPT_ENCODING => '',
//    CURLOPT_MAXREDIRS => 10,
//    CURLOPT_TIMEOUT => 0,
//    CURLOPT_FOLLOWLOCATION => true,
//    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
//    CURLOPT_CUSTOMREQUEST => 'POST',
//    CURLOPT_POSTFIELDS => json_encode([
//      "uid" => $user->uid,
//      "token" => $token,
//      "name" => $account->name,
//      "new_uid" => $account->uid
//    ]),
//    CURLOPT_HTTPHEADER => array(
//      'Content-Type: application/json',
//      'Cookie: _csrf-backend=1d1f189315c04255c97019c8d04a18e4815e9ebf7d68c24e3bf690d637ab0396a%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_csrf-backend%22%3Bi%3A1%3Bs%3A32%3A%22z6qHzQbiby8jcKCzN5VICKAsiwfySN4u%22%3B%7D'
//    ),
//  ));
//
//  $response = curl_exec($curl);
//
//  curl_close($curl);
//
//  dsm($response);

}
function get_thong_tin_chi_tiet_san_pham(){
    //get api san pham ben soft
    $softSanPham = getThongTinSanPham($_POST['san_pham']);

    if (isset($_POST['avatar'])){
        $avatar = $_POST['avatar'];
    }

    $sanPham = node_load($_POST['nid']);
    $title = $sanPham->title;
    $body = drupal_render($sanPham->body);
    $arrImages = '';
    if (!empty($sanPham->field_anh_lien_quan)){
      foreach ($sanPham->field_anh_lien_quan['und'] as $index => $item){
        $path_style = image_style_url('1800_x_1150',$item['uri']);
        $arrImages .= theme_image_style([
          'style_name' => '1800_x_1150',
          'path' => $item['uri'],
          'alt' => $sanPham->title,
          'attributes' => array('class' => 'img-responsive img-fluid'),
          'width' => '1800px',
          'height' => '1150px',
        ]);
      }
    }else{
      $arrImages = theme_image_style([
          'style_name' => '1800_x_1150',
          'path' => $sanPham->field_image['und'][0]['uri'],
          'alt' => $sanPham->title,
          'attributes' => array('class' => 'img-responsive img-fluid'),
          'width' => '1800px',
          'height' => '1150px',
        ]);
    }
    if (!empty($sanPham->field_anh_lien_quan)){
      foreach ($sanPham->field_anh_lien_quan['und'] as $index => $item){
        $path_style = image_style_url('1800_x_1150',$item['uri']);
        $arrImages_desktop .= '<a href="'.$path_style.'" title="'.$sanPham->title.'">'.theme_image_style([
          'style_name' => '1800_x_1150',
          'path' => $item['uri'],
          'alt' => $sanPham->title,
          'attributes' => array('class' => 'img-responsive img-fluid'),
          'width' => '1800px',
          'height' => '1150px',
        ]).'</a>';
      }
    }else{
        $arrImages_desktop = '<a href="'.$path_style.'" title="'.$sanPham->title.'"> '.theme_image_style([
          'style_name' => '1800_x_1150',
          'path' => $sanPham->field_image['und'][0]['uri'],
          'alt' => $sanPham->title,
          'attributes' => array('class' => 'img-responsive img-fluid'),
          'width' => '1800px',
          'height' => '1150px',
        ]).'</a>';
    }

    $strSlider = <<<HTML
                    <div class="d-block d-sm-none">
                        <div class="owl-carousel">
                          {$arrImages}
                        </div>
                    </div>      
                    <div class="d-none d-sm-block">
                        <div class="d-flex image-product-desktop popup-gallery flex-wrap">
                           {$arrImages_desktop}
                        </div>
                    </div>   
HTML;

    $personInCharge = '<div class="person-in-charge">
                            <div class="avatar"><img src="/sites/default/files/'.$avatar.'" class="img-fluid" alt="avatar" title="avatar"></div>
                            <div class="info">
                            <span class="name">'.$softSanPham['nguoi_phu_trach']['ho_ten'].'</span>
                            <a href="tel:'.$softSanPham['nguoi_phu_trach']['dien_thoai'].'" class="phone" data-value="'.$sanPham->nid.'">'.$softSanPham['nguoi_phu_trach']['dien_thoai'].'</a>
                            </div>
                       </div>';
    $detailContent = '<div class="detail-content">
                        <div class="summary mt-30">
                            <h3 class="title">
                                '.$sanPham->title.'
                            </h3>
                            <div class="info-bottom">
                                <span><i class="far fa-calendar-alt"></i> '.date('d/m/Y',$sanPham->field_ngay_dang['und'][0]['value']).'</span>
                                <span><i class="fas fa-eye"></i> '.$softSanPham['san_pham']['luot_xem'].' lượt xem</span>
                            </div>
                            <div class="price-location">
                                <span class="price"><i class="fas fa-money-bill-wave"></i> '.$sanPham->field_gia_bang_chu['und'][0]['value'].'</span>
                                <span class="location-info"><i class="fas fa-map-marker-alt"></i> '.$softSanPham['vi_tri']['dia_chi_cu_the'].'</span>
                            </div>
                            <div class="info-summary">
                                <span><i class="fa fa-expand"></i> '.$sanPham->field_dien_tich_su_dung['und'][0]['value'].' m<sup>2</sup></span>
                                <span><i class="fa fa-bed"></i> '.$sanPham->field_so_giuong['und'][0]['value'].' PN</span>
                                <span><i class="fa fa-bath"></i> '.$sanPham->field_so_phong_tam['und'][0]['value'].' VS</span>
                                <span><i class="fab fa-safari"></i> '.$sanPham->field_huong['und'][0]['value'].'</span>
                            </div>

                        </div>
                        <div class="detail-info">
                           '.$body.'
                           <div class="location-info mt-20">
                                <h3>Vị trí</h3>
                                <div class="item-location"><strong>Tỉnh/Thành phố: </strong><span>'.$softSanPham['vi_tri']['tinh_thanh'].'</span></div>
                                <div class="item-location"><strong>Quận/Huyện: </strong><span>'.$softSanPham['vi_tri']['quan_huyen'].'</span></div>
                                <div class="item-location"><strong>Phường/Xã: </strong><span>'.$softSanPham['vi_tri']['duong_pho'].'</span></div>
                                <div class="item-location"><strong>Địa chỉ cụ thể: </strong><span>'.$softSanPham['vi_tri']['dia_chi_cu_the'].'</span></div>
                           </div>
                        </div>
                      </div>';
    $content = <<<HTML
        <div class="detail-product">
          <div class="row">
              <div class="col-md-6">
                        {$strSlider}
              </div>
              <div class="col-md-6">
                <div class="content">
                    {$personInCharge}
                    {$detailContent}
                </div>    
              </div>
          </div>
          
        </div>
HTML;

    $arr = array(
        'content' => $content,
        'title' =>$title
    );
    echo json_encode($arr);
}

function update_status_user(){
    if (!empty($_GET['uid'])){
    $user = user_load($_GET['uid']);
    $user->status = 0;
    $edit = array();
    user_save($user,$edit);
    }
}
function update_status_product(){
    $check = '';
    $reponse = '';
    if (isset($_POST['ids'])&&isset($_POST['status'])) {
        if (!is_array($_POST['ids'])){
            $reponse = "Dữ liệu phải là mảng.";
        }else{
            $nodes = node_load_multiple($_POST['ids']);
            foreach ($nodes as $node) {
                // set status property to 1
                $node->status = $_POST['status'];
                // re-save the node
                node_save($node);
                $reponse =  "Lưu thành công.";
            }
        }
    }else{
        $reponse = "Chưa có dữ liệu sản phẩm.";
    }
    return drupal_json_output($reponse);
}
function delete_product(){
    $reponse = '';
    if (!empty($_POST['nid'])) {
        if (!is_array($_POST['nid'])){
            $reponse = "Dữ liệu phải là mảng.";
        }else{
            foreach ($_POST['nid'] as $nid){
                node_delete($nid);
            }
            $reponse = "Dữ liệu đã được xoá thành công";
        }
    }else{
        $reponse = "Chưa có dữ liệu nid.";
    }
    return $reponse;
}

